version: '3.5'

services:
  db:
    image: postgres:10.4
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - PGPASSWORD=mysecretpassword1234
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
  api:
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app
      - ./api/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build: ./front
    command: yarn start
    volumes:
      - ./front:/app
    ports:
      - 8000:3000
volumes:
  postgres-data:
    driver: local