default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mysecretpassword1234
  pool: 5

development:
  <<: *default
  database: testdb

test:
  <<: *default
  database: testdb

production:
  <<: *default
  database: api_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
